var properties = PropertiesService.getScriptProperties();
var NOTION_TOKEN = properties.getProperty('NOTION_TOKEN');
var DATABASE_ID = properties.getProperty('DATABASE_ID');
var LINE_ACCESS_TOKEN = properties.getProperty('LINE_ACCESS_TOKEN');
var APP_SECRET = properties.getProperty('APP_SECRET') || "my-secret-key"; 
var ALLOWED_USERS = properties.getProperty('ALLOWED_USERS') ? properties.getProperty('ALLOWED_USERS').split(',') : []; 
var PET_NAME = properties.getProperty('PET_NAME') || "紀錄對象"; 
var GEMINI_API_KEY = properties.getProperty('GEMINI_API_KEY');
var LIFF_CHANNEL_ID = properties.getProperty('LIFF_CHANNEL_ID');
