const properties = PropertiesService.getScriptProperties();
const NOTION_TOKEN = properties.getProperty('NOTION_TOKEN');
const DATABASE_ID = properties.getProperty('DATABASE_ID');
const LINE_ACCESS_TOKEN = properties.getProperty('LINE_ACCESS_TOKEN');
const APP_SECRET = properties.getProperty('APP_SECRET') || "my-secret-key"; 
const ALLOWED_USERS = properties.getProperty('ALLOWED_USERS') ? properties.getProperty('ALLOWED_USERS').split(',') : []; 
const PET_NAME = properties.getProperty('PET_NAME') || "紀錄對象"; 
const GEMINI_API_KEY = properties.getProperty('GEMINI_API_KEY');
const LIFF_CHANNEL_ID = properties.getProperty('LIFF_CHANNEL_ID');
